/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deceasedframes;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import mypanels.Reporterpanel;
import mypanels.kinpanel;
import mypanels.Bodyinformation;

/**
 *
 * @author kibra
 */
public class deceased extends javax.swing.JInternalFrame {
    GridBagLayout layout = new GridBagLayout();
    Reporterpanel p1;
    kinpanel p2;
    Bodyinformation p3;

    /**
     * Creates new form deceased
     */
    public deceased() {
        initComponents();
        p1 = new Reporterpanel();
        p2 = new kinpanel();
        p3 = new Bodyinformation();
        dynamicdeceased.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        dynamicdeceased.add(p1,c);
        dynamicdeceased.add(p2,c);
        dynamicdeceased.add(p3,c);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dynamicdeceased = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Deceased");

        dynamicdeceased.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout dynamicdeceasedLayout = new javax.swing.GroupLayout(dynamicdeceased);
        dynamicdeceased.setLayout(dynamicdeceasedLayout);
        dynamicdeceasedLayout.setHorizontalGroup(
            dynamicdeceasedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        dynamicdeceasedLayout.setVerticalGroup(
            dynamicdeceasedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        getContentPane().add(dynamicdeceased, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dynamicdeceased;
    // End of variables declaration//GEN-END:variables
}
