/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deceasedframes;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author kibra
 */
public class pathologyframe extends javax.swing.JInternalFrame {

    /**
     * Creates new form pathologyframe
     */
    public pathologyframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        addnewpathology = new javax.swing.JButton();
        readpathology = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textpathology = new javax.swing.JTextArea();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pathology");
        setAutoscrolls(true);

        jButton4.setText("Print");

        jButton5.setText("Save");

        addnewpathology.setText("add new");
        addnewpathology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewpathologyActionPerformed(evt);
            }
        });

        readpathology.setText("Search");
        readpathology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readpathologyActionPerformed(evt);
            }
        });

        textpathology.setColumns(20);
        textpathology.setRows(5);
        textpathology.setText("5fr4drcrf5CF54FR54RF54XFR54FR54XF54FTT54F\nTGC5.,4NCFCR54\nCRN54;'CDN4VBN;'DSCV4N]\nCVBN4,CDN,SVB4N]\nCVBN,4CVBSNDL;C ,BD,R 4;CM P[;CV,.NCV,[BN;,.C;',N.CFGHNCVVBN\nXCBVXN],BFN]     JHNVBYJHGJHBJH JN \n\nJKN JKNKL LK \n\nJKL KJL JHNB JHNKLMK,]\n[\n\nJ JHB KJNVGXDDFXB ';\nM BN HGBBKJLMNL;\n\nJMN NB JHNBJKLMN\nLKNJHBJHNL;\n]\nBHV JHBJKN\n]\n\n\n\n JHVBJKNKLNJKN]\n\nLBJKBJKNKL;,\n]JKBJKNLK;MKLM\n;KLM;\n]");
        jScrollPane1.setViewportView(textpathology);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addnewpathology)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 564, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(readpathology)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addGap(66, 66, 66))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(readpathology))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(addnewpathology))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void readpathologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readpathologyActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
            chooser.showOpenDialog(null);
            File f=chooser.getSelectedFile();
            String filename=f.getAbsolutePath();
            
            try {
                FileReader reader = new FileReader(filename);
                BufferedReader br = new BufferedReader(reader);
                textpathology.read(br, null);
                        textpathology.requestFocus();
        }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
                    
    }//GEN-LAST:event_readpathologyActionPerformed

    private void addnewpathologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewpathologyActionPerformed
        // TODO add your handling code here:
          
        try {
                FileWriter write = new FileWriter("\"C:\\Users\\kibra\\Documents\\NetBeansProjects\\project\\Funeral Home Management System 1\\pathology\"");
                BufferedWriter bw = new BufferedWriter(write);
                textpathology.write(bw);
                textpathology.setText("");
                textpathology.requestFocus();
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
           
    }//GEN-LAST:event_addnewpathologyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnewpathology;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton readpathology;
    private javax.swing.JTextArea textpathology;
    // End of variables declaration//GEN-END:variables
}
